### PR TITLE
Chmod +x on Rclone.sh file

### PR DESCRIPTION
**Pull request by bjonness406**
Then you can add your own Rclone.sh file to the /Config folder, then add /config/Rclone.sh to "Sync Command" variable. 
You can then add your own Rclone commands in a .sh file, instead of adding everything as a variable.

### CODE REVIEW

**Review by tynor88 — COMMENTED** [review]
Have you tried building this? I suppose this will fail as you are chmodding a file which does not exist. Maybe touch it first and then chmod. That's the approach i used.

**Comment by bjonness406** [comment]
Yep, it works fine. You just get an message about in in the log if there is no file.
`chmod: /config/Rclone.sh: No such file or directory`

Full output then looks like:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

GID/UID
-------------------------------------
User uid: 911
User gid: 911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-config: executing...
crontab => * * * * * /app/rclone.sh
chmod: /config/Rclone.sh: No such file or directory
[cont-init.d] 40-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

If you want to try it, I made a test docker here: https://hub.docker.com/r/bjonness406/rclone/

**Comment by tynor88** [comment]
Thanks for the PR, it is merged now.

Maybe we can make it more smart, with having a variable called "CUSTOM_SYNC_FILE" which then gets created (if it doesn't exist), chmod'ed and added to the default sync command?

**Comment by bjonness406** [comment]
Not sure how you do that, but that would be very nice. If not, you can just touch the file: "touch /config/Rclone.sh", and write in the description that you can add "/config/Rclone.sh" to sync command to use a file instead.

Then you will also get rid of the warning message in the log.

**Pull request merged**
